version: '3'
services:

  celery_service:
    build: .
    container_name: celery_container
    env_file: "./env.env"
    command: celery -A src.celery_app worker --loglevel=info
    depends_on:
      - redis_service

  flower_service:
    build: .
    container_name: flower_container
    env_file: "./env.env"
    command: celery -A src.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis_service
      - celery_service

  redis_service:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
